---
- src: andrewrothstein.anaconda
  version: v3.0.0
- src: andrewrothstein.supervisord
  version: v1.0.10
- src: andrewrothstein.jupyter-supervisord
  version: v3.0.0
  


                                    
