---
- src: andrewrothstein.sudoers
- src: andrewrothstein.epel
- src: andrewrothstein.ntp
- src: andrewrothstein.nettools
- src: andrewrothstein.git
- src: andrewrothstein.docker
- src: andrewrothstein.docker-py
- src: andrewrothstein.useraccounts
- src: andrewrothstein.emacs-build

                                    
